In [1]:
import numpy as np


1. What is a Python library? Why do we use Python libraries?



A Python library is a collection of pre-written code, functions, and modules that can be imported and used in Python programs to perform specific tasks or functions without the need to write the code from scratch. Libraries provide a set of reusable tools and functionalities that can save time and effort for developers such as `reusablity, Time saving, community contributions`



2. What is the difference between Numpy array and List?



NumPy arrays and Python lists are both used to store and manipulate collections of elements, but there are several key differences between them:

**Data Type:**

**List:** Lists in Python can contain elements of different data types. You can have a mix of integers, strings, booleans, etc., within a single list.

**NumPy Array:** NumPy arrays are homogeneous, meaning all elements must be of the same data type. This homogeneity allows for more efficient storage and operations on the data.

**Performance:**

**List:** Lists are more flexible but may not be as efficient for numerical computations and large datasets.

**NumPy Array:** NumPy arrays are designed for numerical operations and are implemented in C, which makes them more efficient for mathematical computations, especially with large datasets.

**Functionality:**

**List:** Lists provide a general-purpose, flexible container with a variety of built-in methods for manipulation.

**NumPy Array:** NumPy arrays come with a wide range of mathematical functions and operations for array manipulation, making them well-suited for numerical computing.

**Syntax:**

**List:** Lists are part of the core Python language, and their syntax is more straightforward for basic operations.

**NumPy Array:** NumPy provides a dedicated array object with its own syntax and functions, optimized for numerical operations.

Example
```
# Using Python Lists
python_list = [1, 2, 3, 4, 5]
python_list_squared = [x**2 for x in python_list]

# Using NumPy Arrays
import numpy as np
numpy_array = np.array([1, 2, 3, 4, 5])
numpy_array_squared = numpy_array**2

```




3. Find the shape, size and dimension of the following array?

```
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]
```




In [ ]:
np_array=np.array(
[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])
#finding shape, size and dimension
Shape=np_array.shape
size=np_array.size
dim=np_array.ndim
print(f"the shape is {Shape} the size is {size} and the dimesion is {dim}")

the shape is (3, 4) the size is 12 and the dimesion is 2


4. Write python code to access the first row of the following array?


```
[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]

```




In [ ]:
np_array=np.array(
[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

#accessing the first row
print('First row',np_array[0])

First row [1 2 3 4]


5. How do you access the element at the third row and fourth column from the given numpy array?


```
[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]
```




In [ ]:
np_array=np.array(
[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

#accessing the last element from the last row
print("last element", np_array[2,3])

last element 12


6. Write code to extract all odd-indexed elements from the given numpy array?


```
[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]
```




In [ ]:
np_array=np.array(
[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

odd_indexed=np_array[:, 1::2]
print(odd_indexed)

[[ 2  4]
 [ 6  8]
 [10 12]]


In the above example the `odd_indexed=np_array[: ,1::2]` the fist part which is ` : ` is to access the rows(here which means to access all rows) and the next part which is `1::2` is to access the columns(here which means to access the numbers present on the odd positions).

7. How can you generate a random 3x3 matrix with values between 0 and 1?


In [ ]:
import numpy as np
random_matrix = np.random.rand(3, 3)

print("Random 3x3 Matrix:")
print(random_matrix)


Random 3x3 Matrix:
[[0.67984955 0.74816728 0.2968289 ]
 [0.53148311 0.15648222 0.1900292 ]
 [0.76954302 0.1941537  0.54977086]]


in the above example we use random.rand to generate a 3*3 matrix as this method allows us to create matirx of however dimension we want we can even create a matirx of 2-D and 3-D

8. Describe the difference between np.random.rand and np.random.randn?


9. Write code to increase the dimension of the following array?


```
[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]
```



In [ ]:
arr=np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])
newarr=arr.reshape(2,2,3)
print(f"the new array is {newarr} \n with new dimension of {newarr.ndim}")

the new array is [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 
 with new dimension of 3


10. How to transpose the following array in NumPy?


```
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

```



In [ ]:
arr=np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])
transpose_array=arr.transpose()
print(f'the transpose is {transpose_array}')

the transpose is [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


11. Consider the following matrix:

```
Matrix A:
 [[1, 2, 3, 4],
 [5, 6, 7, 8],
 [9, 10, 11, 12]]

```
```
Matrix B:
 [[1, 2, 3, 4],
 [5, 6, 7, 8],
 [9, 10, 11, 12]]`
```
Perform the following operation using Python

1.   Index wise multiplication
2.   Matrix multiplication
3.   Add both matrics
4.   Subtract matrix B from A
5.   Divide matirx B by A


In [ ]:
matrix_A=np.array( [[1, 2, 3, 4],
 [5, 6, 7, 8],
 [9, 10, 11, 12]])

matrix_B=np.array( [[1, 2, 3, 4],
 [5, 6, 7, 8],
 [9, 10, 11, 12]])

# 1) index wise multiplication for this the matrix should be of same diemension

# Ensure matrices have the same dimensions
if len(matrix_A) != len(matrix_B) or len(matrix_A[0]) != len(matrix_B[0]):
  raise ValueError("Matrices must have the same dimensions for element-wise multiplication.")

# Get the dimensions of the matrices
rows, cols = len(matrix_A), len(matrix_A)

# Create a new matrix to store the result
result_matrix = [[0 for _ in range(cols)] for _ in range(rows)]

# Iterate over each element and perform the multiplication
for i in range(rows):
  for j in range(cols):
    result_matrix[i][j] = matrix_A[i][j] * matrix_B[i][j]

# Display the result
print("Matrix A:")
for row in matrix_A:
    print(row)

print("\nMatrix B:")
for row in matrix_B:
    print(row)

print("\nElement-wise Multiplication Result:")
for row in result_matrix:
    print(row)

Matrix A:
[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]

Matrix B:
[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]

Element-wise Multiplication Result:
[1, 4, 9]
[25, 36, 49]
[81, 100, 121]


In [6]:
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

B = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13,14,15,16]])

m=A @ B
print(m)

[[ 90 100 110 120]
 [202 228 254 280]
 [314 356 398 440]]


In [7]:
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

B = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13,14,15,16]]) # adding another row as for matirx the number of columns of A must equal the number of rows of B.

print("Shape of A:", A.shape)
print("Shape of B:", B.shape)


# Performing matrix multiplication using @ operator
multiplied_matrix = A @ B

# # Display the result
print(multiplied_matrix)


Shape of A: (3, 4)
Shape of B: (4, 4)
[[ 90 100 110 120]
 [202 228 254 280]
 [314 356 398 440]]


In [ ]:
import numpy as np

# Define matrices A and B
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

B = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

# Add both matrices
addition_result = A + B

# Subtract matrix B from A
subtraction_result = A - B

# Divide matrix B by A element-wise
division_result = np.divide(B, A)

# Display the results
print("Addition Result:")
print(addition_result)

print("\nSubtraction Result:")
print(subtraction_result)

print("\nDivision Result:")
print(division_result)


Addition Result:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

Subtraction Result:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Division Result:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


12. Which function in Numpy can be used to swap the byte order of an array?


In [ ]:
import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3, 4], dtype=np.int32)

# Swap the byte order
arr_swapped = arr.byteswap()

# Display the original and swapped arrays
print("Original Array:")
print(arr)

print("\nSwapped Byte Order Array:")
print(arr_swapped)


Original Array:
[1 2 3 4]

Swapped Byte Order Array:
[16777216 33554432 50331648 67108864]


13. What is the significance of the np.linalg.inv function?


The np.linalg.inv function in NumPy is used to compute the (multiplicative) inverse of a square matrix. If a matrix A is invertible, the result of np.linalg.inv(A) is a matrix B such that the product of A and B is the identity matrix.

The significance of np.linalg.inv lies in various areas of linear algebra and mathematical modeling. Here are some key points:

**Solving Linear Systems:**

One common use of matrix inversion is in solving systems of linear equations. Given a system of equations in the form Ax = B, where A is the coefficient matrix and B is the vector of constants, you can find the solution x by calculating x = np.linalg.inv(A) @ B.

**Eigenvalue Problems:**

In the context of eigenvalue problems, matrix inversion is often used. The eigenvectors of a matrix A can be obtained by diagonalizing it, and the diagonalization involves the inverse of the matrix.

**Numerical Stability:**

While the concept of matrix inversion is straightforward, calculating the inverse numerically can be sensitive to rounding errors, and not all matrices have an inverse. Therefore, using np.linalg.inv from NumPy provides a reliable and efficient implementation that takes care of numerical stability issues.


In [ ]:
# Define a 2x2 invertible matrix
A = np.array([[2, 1],
              [7, 4]])

# Calculate the inverse using np.linalg.inv
A_inv = np.linalg.inv(A)

# Check if the product of A and A_inv is the identity matrix
identity_matrix = A @ A_inv

print("Original Matrix A:")
print(A)

print("\nInverse Matrix A_inv:")
print(A_inv)

print("\nProduct of A and A_inv (should be identity matrix):")
print(identity_matrix)


Original Matrix A:
[[2 1]
 [7 4]]

Inverse Matrix A_inv:
[[ 4. -1.]
 [-7.  2.]]

Product of A and A_inv (should be identity matrix):
[[1. 0.]
 [0. 1.]]


14. What does the np.reshape function do, and how is it used?


The `np.reshape` function in NumPy is used to change the shape of an array without changing its data. It returns a new array with the same data but a different shape. The function takes the desired shape as an argument, and it is important that the total number of elements in the reshaped array remains the same as in the original array.

`numpy.reshape(a, newshape, order='C')`

`a`: The array to be reshaped.

`newshape`: The new shape to which the array should be reshaped.

`order`: Optional parameter specifying the order to read elements in the original array. It can be 'C' (default) for row-major order, or 'F' for column-major order.

In [ ]:
# Create a 1D array
original_array = np.array([1, 2, 3, 4, 5, 6])

# Reshape to a 2D array with 2 rows and 3 columns
reshaped_array = np.reshape(original_array, (2, 3))

print("Original Array:")
print(original_array)

print("\nReshaped Array:")
print(reshaped_array)


Original Array:
[1 2 3 4 5 6]

Reshaped Array:
[[1 2 3]
 [4 5 6]]


15. What is broadcasting in Numpy?

Broadcasting in NumPy allows you to perform operations on arrays of different shapes, making it easier and more concise. Broadcasting automatically expands smaller arrays to match the shape of larger arrays. Here's a basic guide on how to apply broadcasting in NumPy

**Broadcasting Rules:**

**Dimensions Compatibility:**
For broadcasting to work, the dimensions of the arrays must be compatible. Starting from the trailing dimensions, the size of each dimension must be either the same or one of them should be 1.

**Size Compatibility:**
If a dimension size is 1, it can be expanded to match the size of the other array's dimension.


In [ ]:
# 2D array (3x3)
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

# Scalar value
scalar_value = 10

# Broadcasting: Add scalar to each element
result = array_2d + scalar_value

print("Original 2D Array:")
print(array_2d)

print("\nResult after Broadcasting:")
print(result)


Original 2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Result after Broadcasting:
[[11 12 13]
 [14 15 16]
 [17 18 19]]
